<a href="https://colab.research.google.com/github/HRJ369/CL249--Computational-Lab/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

# Define the matrix A
A = np.array([[2, 3, 1, 4, 5],
              [6, 13, 5, 19, 8],
              [2, 19, 13, 17, 3],
              [8, 3, 5, 25, 1],
              [4, 4, 3, 7, 15]])

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    multiplication_count = 0
    addition_count = 0

    for i in range(n):
        for k in range(i, n):
            sum_u = 0
            for j in range(i):
                sum_u += L[i][j] * U[j][k]
                multiplication_count += 1
            U[i][k] = A[i][k] - sum_u
            addition_count += 1

        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                sum_l = 0
                for j in range(i):
                    sum_l += L[k][j] * U[j][i]
                    multiplication_count += 1
                L[k][i] = (A[k][i] - sum_l) / U[i][i]
                addition_count += 1

    return L, U, multiplication_count, addition_count

def forward_substitution(L, b):
    n = len(b)
    x = np.zeros(n)

    multiplication_count = 0
    addition_count = 0

    for i in range(n):
        sum_l = 0
        for j in range(i):
            sum_l += L[i][j] * x[j]
            multiplication_count += 1
        x[i] = (b[i] - sum_l) / L[i][i]
        addition_count += 1

    return x, multiplication_count, addition_count

def backward_substitution(U, b):
    n = len(b)
    x = np.zeros(n)

    multiplication_count = 0
    addition_count = 0

    for i in reversed(range(n)):
        sum_u = 0
        for j in range(i+1, n):
            sum_u += U[i][j] * x[j]
            multiplication_count += 1
        x[i] = (b[i] - sum_u) / U[i][i]
        addition_count += 1

    return x, multiplication_count, addition_count

def invert_lower(L):
    n = L.shape[0]
    L_inv = np.zeros_like(L)
    I = np.eye(n)

    total_multiplications = 0
    total_additions = 0

    for i in range(n):
        col_inv, mult, add = forward_substitution(L, I[:, i])
        L_inv[:, i] = col_inv
        total_multiplications += mult
        total_additions += add

    return L_inv, total_multiplications, total_additions

def invert_upper(U):
    n = U.shape[0]
    U_inv = np.zeros_like(U)
    I = np.eye(n)

    total_multiplications = 0
    total_additions = 0

    for i in range(n):
        col_inv, mult, add = backward_substitution(U, I[:, i])
        U_inv[:, i] = col_inv
        total_multiplications += mult
        total_additions += add

    return U_inv, total_multiplications, total_additions

# Perform LU decomposition
L, U, lu_mult, lu_add = lu_decomposition(A)

# Inverse of L and U
L_inv, L_inv_mult, L_inv_add = invert_lower(L)
U_inv, U_inv_mult, U_inv_add = invert_upper(U)

# Final inverse of A (A_inv = U_inv * L_inv)
A_inv = np.dot(U_inv, L_inv)

# Output the results
print("Original Matrix A:")
print(A)

#print("\nLower Triangular Matrix L:")
#print(L)

#print("\nUpper Triangular Matrix U:")
#print(U)

#print("\nInverse of Lower Triangular Matrix L:")
#print(L_inv)

#print("\nInverse of Upper Triangular Matrix U:")
#print(U_inv)

print("\nInverse of Matrix A (computed as U_inv * L_inv):")
print(A_inv)

# Output total number of operations
total_multiplications = lu_mult + L_inv_mult + U_inv_mult
total_additions = lu_add + L_inv_add + U_inv_add
total_operations = total_multiplications + total_additions
print(f"\nTotal number of multiplications: {total_multiplications}")
print(f"Total number of additions: {total_additions}")
print("Total number of operations:", total_operations)



Original Matrix A:
[[ 2  3  1  4  5]
 [ 6 13  5 19  8]
 [ 2 19 13 17  3]
 [ 8  3  5 25  1]
 [ 4  4  3  7 15]]

Inverse of Matrix A (computed as U_inv * L_inv):
[[ 4.95189355 -1.20607301  0.22603207  0.27038553 -1.07062436]
 [ 0.45854657  0.00682361  0.0156943  -0.045377   -0.15660184]
 [ 1.16171955 -0.49164108  0.16922552  0.11941317 -0.16683726]
 [-1.83930399  0.4756056  -0.10610713 -0.06277721  0.38485159]
 [-0.81678608  0.19617878 -0.04878881 -0.05458888  0.24769703]]

Total number of multiplications: 130
Total number of additions: 75
Total number of operations: 205


In [28]:
import numpy as np

# Given matrix from the image
A = np.array([
    [25.5, 10.5, 1.05],
    [15.2, 18.7, 0.99],
    [-5.1, 8.9, 1.0]
])

# Number of rows
n = A.shape[0]

# Initialize L and U matrices
L = np.eye(n)  # L is initialized as an identity matrix
U = np.zeros_like(A)

# Perform the LU decomposition
for i in range(n):
    # Upper triangular matrix U
    for k in range(i, n):
        U[i, k] = A[i, k] - np.sum(L[i, :i] * U[:i, k])

    # Lower triangular matrix L
    for k in range(i + 1, n):
        L[k, i] = (A[k, i] - np.sum(L[k, :i] * U[:i, i])) / U[i, i]

# Compute the inverse of L and U
L_inv = np.linalg.inv(L)
U_inv = np.linalg.inv(U)

# Multiply the inverses
result = np.dot(U_inv, L_inv)

# Print L, U, their inverses, and the result
print("The matrix A = ")
print(A)
#print("L:\n", L)
#print("U:\n", U)
#print("L_inv:\n", L_inv)
#print("U_inv:\n", U_inv)
print("Inv_A:\n", result)

P1 = np.array([
    [12],
    [8],
    [10]
])
print("Pipes for day 1 = ")
print(P1)

P2 = np.array([
    [11],
    [7],
    [11]
])
print("Pipes for day 15 = ")
print(P2)

P3 = np.array([
    [10],
    [10],
    [10]
])
print("Pipes for day 30 = ")
print(P3)

Day1 = np.dot(result, P1)
Day15 = np.dot(result, P2)
Day30 = np.dot(result, P3)

print(" Values of x , y , z for day 1 = ")
print(Day1)

print(" Values of x , y , z for day 15 = ")
print(Day15)

print(" Values of x , y , z for day 30 = ")
print(Day30)


The matrix A = 
[[25.5  10.5   1.05]
 [15.2  18.7   0.99]
 [-5.1   8.9   1.  ]]
Inv_A:
 [[ 0.03510005 -0.00409956 -0.03279649]
 [-0.07187187  0.10951684 -0.03295621]
 [ 0.81866986 -0.99560761  1.12604818]]
Pipes for day 1 = 
[[12]
 [ 8]
 [10]]
Pipes for day 15 = 
[[11]
 [ 7]
 [11]]
Pipes for day 30 = 
[[10]
 [10]
 [10]]
 Values of x , y , z for day 1 = 
[[ 0.06043924]
 [-0.31588979]
 [13.11965926]]
 Values of x , y , z for day 15 = 
[[-3.35773548e-03]
 [-3.86490971e-01]
 [ 1.44226452e+01]]
 Values of x , y , z for day 30 = 
[[-0.01795998]
 [ 0.04688762]
 [ 9.49110431]]
