<a href="https://colab.research.google.com/github/HRJ369/CL249--Computational-Lab/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Define the matrix A
A = np.array([[2, 3, 1, 4, 5],
              [6, 13, 5, 19, 8],
              [2, 19, 13, 17, 3],
              [8, 3, 5, 25, 1],
              [4, 4, 3, 7, 15]])

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        for k in range(i, n):
            sum_u = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - sum_u

        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                sum_l = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (A[k][i] - sum_l) / U[i][i]

    return L, U

def forward_substitution(L, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        x[i] = (b[i] - np.dot(L[i, :i], x[:i])) / L[i, i]
    return x

def backward_substitution(U, b):
    n = len(b)
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = (b[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

def invert_lower(L):
    n = L.shape[0]
    L_inv = np.zeros_like(L)
    I = np.eye(n)

    for i in range(n):
        L_inv[:, i] = forward_substitution(L, I[:, i])

    return L_inv

def invert_upper(U):
    n = U.shape[0]
    U_inv = np.zeros_like(U)
    I = np.eye(n)

    for i in range(n):
        U_inv[:, i] = backward_substitution(U, I[:, i])

    return U_inv

# Perform LU decomposition
L, U = lu_decomposition(A)

# Inverse of L and U
L_inv = invert_lower(L)
U_inv = invert_upper(U)

# Final inverse of A (A_inv = U_inv * L_inv)
A_inv = np.dot(U_inv, L_inv)

# Output the results
print("Original Matrix A:")
print(A)

#print("\nLower Triangular Matrix L:")
#print(L)

#print("\nUpper Triangular Matrix U:")
#print(U)

#print("\nInverse of Lower Triangular Matrix L:")
#print(L_inv)

#print("\nInverse of Upper Triangular Matrix U:")
#print(U_inv)

print("\nInverse of Matrix A (computed as U_inv * L_inv):")
print(A_inv)


Original Matrix A:
[[ 2  3  1  4  5]
 [ 6 13  5 19  8]
 [ 2 19 13 17  3]
 [ 8  3  5 25  1]
 [ 4  4  3  7 15]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.          0.        ]
 [ 3.          1.          0.          0.          0.        ]
 [ 1.          4.          1.          0.          0.        ]
 [ 4.         -2.25        1.375       1.          0.        ]
 [ 2.         -0.5         0.5         0.22038567  1.        ]]

Upper Triangular Matrix U:
[[  2.           3.           1.           4.           5.        ]
 [  0.           4.           2.           7.          -7.        ]
 [  0.           0.           4.         -15.          26.        ]
 [  0.           0.           0.          45.375      -70.5       ]
 [  0.           0.           0.           0.           4.03719008]]

Inverse of Lower Triangular Matrix L:
[[  1.           0.           0.           0.           0.        ]
 [ -3.           1.           0.           0.           0.        ]
 [